### PR TITLE
publish ground truth pose from gazebo

### PR DESCRIPTION
**Pull request by alvinsunyixiao**
Ground truth turtlebot pose from gazebo is now published to `/sim/pose`.

**Note**: our autonomy stack should **not** use this channel since it is not available on hardware.

### CODE REVIEW

**Comment by javieryu** [comment]
Tested on my setup, and works.

**Review by abhyudit309 — COMMENTED** [review]
Looks good! Thanks.

**Review by abhyudit309 — COMMENTED** [review]
Works. Thanks!

**Comment by alvinsunyixiao** [comment]
This is not merged @abhyudit309. Can you approve this?

**Review by abhyudit309 — APPROVED** [review]

**Pull request merged**
